'use strict';
(() => {
 if(document.body.classList.contains('home-page'))return;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),root=document.querySelector('.hero-grid');
 const kind=['energy','inventory','suite','tarifs','console'].find(k=>document.body.classList.contains('page-'+k));
 let stage=null,canvas=null,ctx=null,paused=reduced.matches,visible=true,frame=0,last=0,time=0,w=600,h=650;
 if(kind&&root){const target=root.querySelector(':scope>.hud-panel,:scope>.console-preview');if(target){stage=document.createElement('div');stage.className='product-stage stage-'+kind;target.before(stage);stage.append(target);canvas=document.createElement('canvas');canvas.className='product-mesh';canvas.setAttribute('aria-hidden','true');stage.prepend(canvas);ctx=canvas.getContext('2d');const a=document.createElement('span');a.className='stage-coordinate';a.textContent='FORTHEC° / '+kind.toUpperCase()+'.CORE';const b=document.createElement('span');b.className='stage-coordinate stage-coordinate-right';b.textContent='LOGICIEL / DONNÉES / LIVRABLE';stage.append(a,b)}}
 let phase=0,phaseTime=0,phasePaused=reduced.matches;let phases=[],tabs=[];
 if(kind==='energy'&&stage){const story=document.createElement('div');story.className='engine-sequence';story.setAttribute('aria-label','Illustration du parcours Energy');story.innerHTML=`<div class="engine-phase" data-phase="0"><div class="input-token">CSV<small>CONSOMMATIONS</small></div><div class="input-token">XLSX<small>SOUS-COMPTAGES</small></div><div class="input-token">DATA<small>PRODUCTION</small></div></div><div class="engine-phase" data-phase="1"><svg class="engine-graph" viewBox="0 0 300 100" aria-hidden="true"><path class="graph-grid" d="M10 10V90H290M10 65H290M10 40H290M10 15H290M80 10V90M150 10V90M220 10V90"/><path class="graph-fit" d="M20 82L275 18"/>${[[25,78],[55,76],[75,64],[105,58],[130,57],[155,48],[185,36],[211,38],[243,24],[270,22]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="2.7"/>`).join('')}</svg></div><div class="engine-phase" data-phase="2"><div class="engine-actions"><div><span>Éclairage</span><b>Passage en LED</b></div><div><span>Motorisation</span><b>Variation de vitesse</b></div><div><span>Chaleur</span><b>Électrification</b></div></div></div><div class="engine-phase" data-phase="3"><div class="mini-report"><small>FORTHEC° ENERGY</small><strong>Rapport<br>NF EN 16247</strong><i></i><i></i><i></i></div><div class="report-ready"><b>Votre livrable.</b>Word complet<br>Libre à modifier.</div></div>`;const money=stage.querySelector('.money-readout');money.after(story);const nav=document.createElement('div');nav.className='energy-phase-nav';nav.setAttribute('aria-label','Étapes illustrées');nav.innerHTML=['Import','Calculs','Actions','Rapport'].map((t,i)=>`<button type="button" aria-pressed="false"><span>0${i+1}</span>${t}</button>`).join('');story.after(nav);phases=[...story.children];tabs=[...nav.children];function select(n){phase=n;phaseTime=0;phases.forEach((p,i)=>{p.classList.toggle('active',i===n);p.setAttribute('aria-hidden',i!==n)});tabs.forEach((t,i)=>t.setAttribute('aria-pressed',i===n))}tabs.forEach((t,i)=>t.addEventListener('click',()=>{phasePaused=true;paused=true;select(i);label()}));stage.selectPhase=select;select(reduced.matches?3:0);const disclosure=document.createElement('p');disclosure.className='scene-disclosure';disclosure.textContent='Parcours illustratif. Téléchargez le vrai rapport pour juger le résultat.';nav.after(disclosure)}
 if(kind==='suite'&&stage){const net=document.createElement('div');net.className='suite-network';net.setAttribute('aria-label','Inventory transmet les équipements à Energy pour enrichir le rapport');net.innerHTML=`<div class="suite-floor" aria-hidden="true"></div><svg class="suite-links" viewBox="0 0 400 220" aria-hidden="true"><path d="M65 120L195 65L340 140"/><path class="travel" d="M65 120L195 65L340 140"/></svg><article class="suite-node"><small>01 / TERRAIN</small><b>Inventory</b><em>Équipements réels</em></article><article class="suite-node"><small>02 / AUDIT</small><b>Energy</b><em>Calculs + actions</em></article><article class="suite-node"><small>03 / LIVRABLE</small><b>Rapport</b><em>Word sur mesure</em></article>`;stage.querySelector('.hud-panel-head').after(net)}
 if(kind==='tarifs'&&stage){const orbit=document.createElement('div');orbit.className='roi-orbit';orbit.innerHTML='<span><b>1</b> audit type</span><i>→</i><span><b>8</b> mois Solo Energy</span>';stage.querySelector('.roi-bars').after(orbit)}
 if(kind==='console'&&stage){const team=document.createElement('div');team.className='console-team';team.setAttribute('aria-label','Illustration des membres d’une même organisation');team.innerHTML='<span>01</span><i></i><span>02</span><i></i><span>03</span>';stage.querySelector('.mock-title-1').after(team);const share=document.createElement('div');share.className='console-share';share.innerHTML='<span>RAPPORT DÉPOSÉ</span><i></i><b>ÉQUIPE</b>';stage.querySelector('.app-mockup-lab-content').append(share)}
 if(document.body.classList.contains('page-contact')&&root){const signal=document.createElement('div');signal.className='contact-signal';signal.innerHTML='<div class="signal-ring" aria-hidden="true"></div><div class="signal-ring" aria-hidden="true"></div><div class="signal-card"><span>DÉMONSTRATION FORTHEC°</span><strong>Vos données.<br>Votre prochain<br>rapport.</strong><p>Un échange direct avec<br>le développeur de vos outils.</p><div class="signal-path"><span>IMPORT</span><i></i><span>RAPPORT</span></div></div><span class="signal-corner">HUGO CHAMBEFORT / ÉDITEUR FRANÇAIS</span>';root.append(signal)}
 if(document.body.matches('.page-article,.page-blog-list,.page-legal')){const title=document.querySelector('.section-title');const spectrum=document.createElement('div');spectrum.className='resource-spectrum';const legal=document.body.classList.contains('page-legal');spectrum.innerHTML='<div class="spectrum-title">FORTHEC° / '+(legal?'CADRE & CONFIANCE':'RESSOURCES POUR LES AUDITEURS')+'<b>'+(legal?'Vos données. Vos droits.':'L’énergie, côté logiciel.')+'</b></div><div class="spectrum-bars" aria-hidden="true">'+Array.from({length:30},(_,i)=>'<i style="--n:'+((i*7)%13+1)+'"></i>').join('')+'</div>';title.after(spectrum)}
 if(!stage)return;
 const buttons=document.createElement('div');buttons.className='scene-controls';buttons.innerHTML='<span>MISE EN SCÈNE / '+kind.toUpperCase()+'</span><button type="button">Pause visuelle</button>';stage.append(buttons);const toggle=buttons.querySelector('button');
 function label(){stage.classList.toggle('scene-paused',paused||phasePaused&&kind==='energy');toggle.textContent=paused?'Animer la scène':'Pause visuelle';toggle.setAttribute('aria-pressed',paused)}
 toggle.addEventListener('click',()=>{paused=!paused;phasePaused=paused;if(!paused&&kind==='energy')stage.selectPhase(phase);label();start()});reduced.addEventListener('change',()=>{paused=reduced.matches;phasePaused=paused;if(paused&&kind==='energy')stage.selectPhase(3);label();draw();start()});
 const verts=[];for(let row=0;row<=10;row++){const a=row*Math.PI/10;for(let col=0;col<22;col++){const b=col*Math.PI*2/22;verts.push([Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)])}}
 function projection(p){const angle=time*.09,ca=Math.cos(angle),sa=Math.sin(angle),x=p[0]*ca-p[2]*sa,z=p[0]*sa+p[2]*ca,y=p[1],tilt=.26;const yy=y*Math.cos(tilt)-z*Math.sin(tilt),zz=y*Math.sin(tilt)+z*Math.cos(tilt);const r=Math.min(w*.44,h*.45),scale=3.2/(3.2-zz*.6);return [w*.51+x*r*scale,h*.49+yy*r*1.1*scale,zz]}
 function draw(){if(!ctx||!w||!h)return;ctx.clearRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.5,h*.5,0,w*.5,h*.5,w*.55);glow.addColorStop(0,'#3eeeac13');glow.addColorStop(1,'#1b806900');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);const points=verts.map(projection);for(let row=0;row<10;row++)for(let col=0;col<22;col++){const a=points[row*22+col],b=points[row*22+(col+1)%22],c=points[(row+1)*22+col];const depth=(a[2]+b[2]+c[2])/3,alpha=.07+(depth+1)*.12;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.lineTo(c[0],c[1]);ctx.closePath();ctx.strokeStyle=`rgba(${col%5===0?'136,232,164':'60,216,205'},${alpha})`;ctx.lineWidth=.65;ctx.stroke();if((row*22+col)%7===0){ctx.fillStyle=`rgba(147,239,178,${.025+(depth+1)*.025})`;ctx.fill()}if((row*22+col)%11===0){ctx.fillStyle='#a8ffcfb3';ctx.fillRect(a[0]-1,a[1]-1,2,2)}}for(let i=0;i<30;i++){const a=i*2.4+time*.025,x=w*.5+Math.cos(a)*w*(.42+(i%3)*.04),y=h*.5+Math.sin(a)*h*(.4+(i%4)*.03);ctx.fillStyle=i%5===0?'#e4d28bab':'#9cf9c799';ctx.fillRect(x,y,i%5===0?2:1,i%5===0?2:1)}}
 function resize(){const box=canvas.getBoundingClientRect();w=box.width;h=box.height;const d=Math.min(devicePixelRatio,1.5);canvas.width=w*d;canvas.height=h*d;ctx?.setTransform(d,0,0,d,0,0);draw()}
 function tick(now){frame=0;if(document.hidden||paused||!visible||document.body.dataset.motion==='paused')return;const delta=Math.min((now-last)/1000,.1);if(now-last>33){last=now;time+=delta;draw();if(kind==='energy'&&!phasePaused){phaseTime+=delta;if(phaseTime>=5.5)stage.selectPhase((phase+1)%4)}}frame=requestAnimationFrame(tick)}
 function start(){if(!frame&&!paused&&visible&&!document.hidden&&document.body.dataset.motion!=='paused'){last=performance.now();frame=requestAnimationFrame(tick)}}
 new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;stage.dataset.visible=visible;start()},{threshold:.05}).observe(stage);new ResizeObserver(resize).observe(stage);new MutationObserver(()=>{label();draw();start()}).observe(document.body,{attributes:true,attributeFilter:['data-motion']});document.addEventListener('visibilitychange',start);label();resize();start();
})();
